### ISSUE TITLE
Microsoft Translator API is Dead

### ISSUE THREAD

**Issue by BugsBunny338** [roman01la/slack-traductor#13]
Microsoft Translator API is no longer working as existing subscriptions were retired and cancelled 3/31/2017. Any plans on adjusting slack-traductor to a different service?

**Comment by roman01la** [comment]
@BugsBunny338 Hello. I don't use it anymore, but I'm happy to accept a PR if you have something in mind on how this problem can be solved.

**Comment by BugsBunny338** [comment]
Thanks for quick answer. Let me check with our Security Director if Google Translator would be suitable from our point of view. If so, I'll try to adjust and pull a request.

**Comment by htilly** [comment]
Hi guys.
Im actually have a bot running using Google translation.
I´ll put it on GitHub =)

https://github.com/htilly/Slack-Translation-Buddy

/Tilly

**Comment by BugsBunny338** [comment]
Thanks, @htilly! Is it possible to issue a PR to this repo? Some of us may have customized the original https://github.com/roman01la/slack-traductor repo and it would be much easier to merge all the changes together.

**Comment by BugsBunny338** [comment]
Also, some README would be helpful. Can't figure out, how to make https://github.com/htilly/Slack-Translation-Buddy running 😞

**Comment by htilly** [comment]
Can you do a "git pull" and try again ?
Also updated the README.

**Comment by BugsBunny338** [comment]
Got it up and running, thx.
