### ISSUE TITLE
Enhancements and configuration

### ISSUE THREAD

**Issue by acontreras89** [roman01la/slack-traductor#2]
List of possible improvements (from bare ideas to ongoing work) for the bot. Place for discussion.
- [ ] Turn on/off the bot
- [x] Specify target language
- [ ] Specify source languages
- [ ] Sanitize input (see #1)
- [ ] Translation on demand?
- [ ] Add support for different APIs (e.g. Google Translate)

**Comment by roman01la** [comment]
It's possible to specify target language via `TRANSLATE_TO=en` setting in `.env` file.

**Comment by roman01la** [comment]
Not sure if specifying source languages is a good idea. The bot will translate any lang, except the target one. But I could add this option if it's much wanted.

**Comment by acontreras89** [comment]
For now I'm just throwing in ideas :blush:

Sorry I missed the `TRANSLATE_TO` option. I've checked that item now.

**Comment by roman01la** [comment]
no work is going to be done here, closing
