### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by victorpavlenko** [roman01la/slack-traductor#3]
Hi, I can not connect using your documentation.
I've never used before slack. And for me it is a problem.

It is not clear what bot_name, bot_token and where to take them.
What to write in the URL option on the slack.
(https: // [YOUR_TEAM] .slack.com / services / new / slash-commands here)
And in general, how to configure everything on the slack.

After I run npm start, nothing happens.

Write please more detailed documentation on the connection.

And he added that when connecting pm2 need to use io.js.
Since Flag --next-gen-js does not work in node.js

(By the way, through io I also did not work)

**Comment by roman01la** [comment]
Привет. Можешь пожалуйста переписать вопрос на англ? Я отвечу и это будет подсказкой для остальных, спасибо.

**Comment by victorpavlenko** [comment]
Ок сейчас перепишу

**Comment by roman01la** [comment]
Я ничего не получал. Попробуй отправить на roman01la@romanliutikov.com

**Comment by victorpavlenko** [comment]
1
