### ISSUE TITLE
Layman's Instructions Needed

### ISSUE THREAD

**Issue by daisy613** [roman01la/slack-traductor#6]
Hey there, Roman.  I would love to integrate the bot into our Slack team, but I am not sure I understand all the steps involved.  I added MS Translator to my Live account, but beyond that I am not sure what to do with the ENV file or integration into Slack.  Help, pls?  :)

**Comment by roman01la** [comment]
Hello. Sorry for late response. Take `.env.example` and rename it into `.env` and edit it by following explanations of every field in this file. `bot_name` and `bot_token` are name and token of Slack bot which you should create. Go here https://slack.com/apps/build/custom-integration and select the second type of a bot. Follow the instructions to create a custom bot for your team, you'll find a name and token there. Once you added everything into `env`, continue following instructions in the README to this project.

I'll add this info into the README. Thanks for your interest!
