### ISSUE TITLE
Can we make the messages just visible to one user?

### ISSUE THREAD

**Issue by cggaurav** [roman01la/slack-traductor#7]

**Comment by roman01la** [comment]
Hi. I think you should check if Slack and its API allows it. If it is, you are welcome to submit a pull request with this functionality. I'm not using this tool anymore.

**Comment by cggaurav** [comment]
@roman01la Thanks! Which tool are you using?

**Comment by roman01la** [comment]
@cggaurav I'm not using any tools, we just agreed to communicate in English :)
